# user: nobody
directory: /tmp
# daemonize: yes

poll_interval: 10
update_interval: 5

logger:
  level: debug
  file: stderr

hostid: 31de9f7d766287c7565801f30babbd4f
quanta_token: 76049d1d498e890ad4dd

server:
  url: "http://192.168.99.1:4242/push"
  timeout: 5
  proxy_url: 'http://toto:toto42sh@127.0.0.1:6666'

cache:
  max_size_mb: 30

modules:
  path: /monikor/lib/modules
  # config_path: /tmp
  config_path: /monikor/etc/modules/

listen:
  path: /tmp/monikor.sock
  user: www-data
  mode: 0666
