user: nobody
directory: /var/run/quanta-agent
daemonize: no

poll_interval: 10
update_interval: 5

logger:
  level: debug
  file: stderr

hostid: 0242ac110001
quanta_token: 76049d1d498e890ad4dd

server:
  url: "http://192.168.99.1:4242/push"
  timeout: 5

cache:
  max_size_mb: 30

modules:
  path: /usr/lib/quanta/modules
  config_path: /etc/quanta/modules.d

listen:
  path: /var/run/monikor.sock
  user: nobody
  group: www-data
  mode: 0660
