hostname: monhostname

user: nobody
daemonize: no

directory: /tmp
pidfile: /tmp/toto.pid

poll_interval: 60
update_interval: 10

logger:
  level: debug
  file: stderr

hostid: 35546b3fc238
quanta_token: 76049d1d498e890ad4dd

server:
  url: "http://192.168.99.1:4242/push"
  timeout: 5

cache:
  max_size_mb: 30

modules:
  path: /usr/lib/x86_64-linux-gnu/
  config_path: /tmp

listen:
  path: /tmp/monikor.sock
  user: nobody
  group: www-data
  mode: 0660
